module.exports = {
  apps: [
    {
      name: "influencer-onboarding-frontend",
      script: "npm",
      args: "run preview",
      cwd: "./packages/frontend",
      env: {
        NODE_ENV: "production",
        PORT: 3060,
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/frontend-err.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: "influencer-onboarding-backend",
      script: "npm",
      args: "start",
      cwd: "./packages/backend",
      env: {
        NODE_ENV: "production",
        PORT: 3060,
        SUPABASE_URL: "https://qwbyfckieoxlzuoyigjh.supabase.co",
        SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YnlmY2tpZW94bHp1b3lpZ2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzEyMTAsImV4cCI6MjA2MzkwNzIxMH0.a5d7zwVT3utCQx3kNe-6knU7S-Tf9F_M1-9Zu4pC94I",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/backend-err.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};
